

export const KEYWORDS = {
  // ============ PROGRAMMAZIONE — Linguaggi ============
  javascript: 8,
  typescript: 8,
  java: 8,
  'c#': 8,
  csharp: 8,
  '.net': 8,
  dotnet: 8,
  python: 7,
  'c++': 7,
  cpp: 7,
  php: 7,
  ruby: 6,
  go: 7,
  golang: 7,
  rust: 7,
  kotlin: 6,
  swift: 6,
  scala: 6,
  'r': 5,
  matlab: 5,

  // ============ PROGRAMMAZIONE — Framework e piattaforme ============
  react: 8,
  'next.js': 8,
  nextjs: 8,
  vue: 7,
  'vue.js': 7,
  angular: 7,
  'node.js': 8,
  nodejs: 8,
  express: 6,
  nestjs: 7,
  laravel: 7,
  symfony: 7,
  django: 7,
  flask: 7,
  rails: 7,
  'ruby on rails': 7,
  spring: 8,
  'spring boot': 8,
  'asp.net': 7,
  astro: 6,
  flutter: 6,
  'react native': 7,
  xamarin: 6,
  tailwind: 6,
  'tailwind css': 6,
  bootstrap: 4,
  html: 5,
  html5: 5,
  css: 5,
  css3: 5,

  // ============ PROGRAMMAZIONE — Concetti ============
  software: 7,
  applicazione: 6,
  applicativo: 6,
  gestionale: 7,
  gestionali: 7,
  erp: 7,
  crm: 6,
  api: 6,
  'rest api': 6,
  database: 5,
  sql: 6,
  mysql: 6,
  postgresql: 6,
  oracle: 5,
  mongodb: 5,
  nosql: 5,
  docker: 6,
  kubernetes: 6,
  cloud: 5,
  aws: 5,
  azure: 5,
  gcp: 5,
  linux: 4,
  unix: 4,
  git: 5,
  github: 5,
  gitlab: 5,
  devops: 7,
  'ci/cd': 6,
  microservices: 6,
  saas: 6,
  mvc: 5,
  orm: 5,
  testing: 5,
  'unit test': 5,
  automation: 5,
  agile: 4,
  scrum: 4,
  kanban: 4,
  'machine learning': 6,
  ai: 5,
  'intelligenza artificiale': 6,
  blockchain: 5,
  iot: 5,
  cybersecurity: 5,
  'sicurezza informatica': 5,
  networking: 4,
  server: 4,
  sysadmin: 4,
  virtualizzazione: 4,
  vmware: 4,

  // ============ WEB DESIGN ============
  'ui/ux': 8,
  'ui & ux': 8,
  'web design': 8,
  figma: 7,
  design: 6,
  grafica: 6,
  grafico: 6,
  branding: 6,
  'brand identity': 6,
  'visual design': 6,
  'interaction design': 7,
  prototyping: 6,
  prototipazione: 6,
  'user experience': 7,
  ux: 7,
  'user interface': 6,
  ui: 6,
  'responsive design': 6,
  responsive: 5,
  wireframe: 5,
  mockup: 5,
  accessibility: 5,
  accessibilità: 5,
  tipografia: 4,
  layout: 4,

  // ============ WORDPRESS & CMS ============
  wordpress: 8,
  woocommerce: 8,
  cms: 7,
  elementor: 6,
  divi: 6,
  acf: 7,
  'advanced custom fields': 7,
  shopify: 6,
  prestashop: 5,
  magento: 6,
  drupal: 5,
  joomla: 4,

  // ============ RUOLI ============
  'software engineer': 9,
  'software developer': 9,
  'web designer': 8,
  'web developer': 8,
  'full stack': 8,
  fullstack: 8,
  developer: 8,
  sviluppatore: 8,
  programmatore: 8,
  'analista programmatore': 8,
  frontend: 7,
  'front-end': 7,
  backend: 8,
  'back-end': 8,
  designer: 6,
  'system engineer': 7,
  'devops engineer': 8,
  'data engineer': 7,
  'data scientist': 7,
  'tech lead': 7,
  cto: 7,
  architect: 7,
  'consulente informatico': 7,

  // ============ CULTURA TECH ============
  'team di sviluppo': 10,
  'software house': 9,
  'web agency': 9,
  'sviluppo software': 8,
  'sviluppo web': 8,
  'consulenza informatica': 8,
  'servizi informatici': 8,
  'lavora con noi': 8,
  'posizioni aperte': 8,
  careers: 7,
  'join us': 6,
  'we are hiring': 6,

  // ============ WEB / DIGITALE ============
  'sito web': 5,
  'siti web': 5,
  seo: 5,
  'e-commerce': 6,
  ecommerce: 6,
  'landing page': 5,
  'realizzazione siti': 6,

  // ============ MARKETING (basso) ============
  marketing: 3,
  'social media': 2,
  'digital marketing': 3,
  digitale: 2,
  pubblicità: 2,
}

// Cap per keyword: oltre N occorrenze, non conta di più
export const KEYWORD_CAP = 3

// Soglia per considerare un'azienda "tech"
export const SCORE_THRESHOLD = 30

// Quante aziende scansionare per batch
export const BATCH_SIZE = 20